/*
 * Generated browser client for Pro Vision Engine.
 * Do not edit this file manually.
 */

import type {
  CouponAnalysisRunRequest,
  CouponAnalysisRunResponse,
  CouponListResponse,
  CouponReductionRunRequest,
  CouponReductionRunResponse,
  CouponResponse,
  HealthResponse,
} from "./api-types";

export interface ProVisionApiClientOptions {
  baseUrl: string;
  fetchImplementation?: typeof fetch;
}

export class ProVisionApiError extends Error {
  readonly status: number;
  readonly body: unknown;

  constructor(
    message: string,
    status: number,
    body: unknown,
  ) {
    super(message);
    this.name = "ProVisionApiError";
    this.status = status;
    this.body = body;
  }
}

export class ProVisionApiClient {
  private readonly baseUrl: string;
  private readonly fetchImplementation: typeof fetch;

  constructor(options: ProVisionApiClientOptions) {
    this.baseUrl = options.baseUrl.replace(/\/+$/, "");
    this.fetchImplementation =
      options.fetchImplementation ?? fetch;
  }

  getHealth(): Promise<HealthResponse> {
    return this.request<HealthResponse>(
      "GET",
      "/api/v1/health",
    );
  }

  listCoupons(): Promise<CouponListResponse> {
    return this.request<CouponListResponse>(
      "GET",
      "/api/v1/coupons",
    );
  }

  getCoupon(gameType: string): Promise<CouponResponse> {
    const encodedGameType = encodeURIComponent(gameType);

    return this.request<CouponResponse>(
      "GET",
      `/api/v1/coupons/${encodedGameType}`,
    );
  }

  createAnalysisRun(
    request: CouponAnalysisRunRequest,
  ): Promise<CouponAnalysisRunResponse> {
    return this.request<CouponAnalysisRunResponse>(
      "POST",
      "/api/v1/analysis-runs",
      request,
    );
  }

  createReductionRun(
    request: CouponReductionRunRequest,
  ): Promise<CouponReductionRunResponse> {
    return this.request<CouponReductionRunResponse>(
      "POST",
      "/api/v1/reduction-runs",
      request,
    );
  }

  private async request<T>(
    method: "GET" | "POST",
    path: string,
    body?: unknown,
  ): Promise<T> {
    const headers: Record<string, string> = {
      Accept: "application/json",
    };

    if (body !== undefined) {
      headers["Content-Type"] = "application/json";
    }

    const response = await this.fetchImplementation(
      `${this.baseUrl}${path}`,
      {
        method,
        headers,
        body:
          body === undefined
            ? undefined
            : JSON.stringify(body),
      },
    );

    const responseBody = await this.readBody(response);

    if (!response.ok) {
      throw new ProVisionApiError(
        `Pro Vision API request failed with status ${response.status}.`,
        response.status,
        responseBody,
      );
    }

    return responseBody as T;
  }

  private async readBody(
    response: Response,
  ): Promise<unknown> {
    if (response.status === 204) {
      return null;
    }

    const contentType =
      response.headers.get("content-type") ?? "";

    if (contentType.includes("application/json")) {
      return response.json();
    }

    return response.text();
  }
}
