/*
 * Generated browser client for Pro Vision Engine.
 * Do not edit this file manually.
 */

import type {
  CouponListResponse,
  CouponResponse,
  HealthResponse,
} from "./api-types";

export interface ProVisionApiClientOptions {
  baseUrl: string;
  fetchImplementation?: typeof fetch;
}

export class ProVisionApiError extends Error {
  readonly status: number;
  readonly body: unknown;

  constructor(
    message: string,
    status: number,
    body: unknown,
  ) {
    super(message);
    this.name = "ProVisionApiError";
    this.status = status;
    this.body = body;
  }
}

export class ProVisionApiClient {
  private readonly baseUrl: string;
  private readonly fetchImplementation: typeof fetch;

  constructor(options: ProVisionApiClientOptions) {
    this.baseUrl = options.baseUrl.replace(/\/+$/, "");
    this.fetchImplementation =
      options.fetchImplementation ?? fetch;
  }

  getHealth(): Promise<HealthResponse> {
    return this.get<HealthResponse>("/api/v1/health");
  }

  listCoupons(): Promise<CouponListResponse> {
    return this.get<CouponListResponse>("/api/v1/coupons");
  }

  getCoupon(gameType: string): Promise<CouponResponse> {
    const encodedGameType = encodeURIComponent(gameType);

    return this.get<CouponResponse>(
      `/api/v1/coupons/${encodedGameType}`,
    );
  }

  private async get<T>(path: string): Promise<T> {
    const response = await this.fetchImplementation(
      `${this.baseUrl}${path}`,
      {
        method: "GET",
        headers: {
          Accept: "application/json",
        },
      },
    );

    const body = await this.readBody(response);

    if (!response.ok) {
      throw new ProVisionApiError(
        `Pro Vision API request failed with status ${response.status}.`,
        response.status,
        body,
      );
    }

    return body as T;
  }

  private async readBody(
    response: Response,
  ): Promise<unknown> {
    if (response.status === 204) {
      return null;
    }

    const contentType =
      response.headers.get("content-type") ?? "";

    if (contentType.includes("application/json")) {
      return response.json();
    }

    return response.text();
  }
}
