"""TypeScript contract exporter for Pro Vision Engine."""

import json
import re
from pathlib import Path
from typing import Any


class TypeScriptContractError(ValueError):
    """Raised when an OpenAPI document cannot be converted."""


class TypeScriptContractExporter:
    """Generate frontend TypeScript files from OpenAPI."""

    _identifier_pattern = re.compile(
        r"^[A-Za-z_$][A-Za-z0-9_$]*$"
    )

    def types_to_string(
        self,
        openapi_schema: dict[str, Any],
    ) -> str:
        """Generate TypeScript interfaces from OpenAPI schemas."""

        schemas = self._component_schemas(
            openapi_schema
        )
        lines = [
            "/*",
            " * Generated from contracts/openapi.json.",
            " * Do not edit this file manually.",
            " */",
            "",
        ]

        for name in sorted(schemas):
            schema = schemas[name]

            if not isinstance(schema, dict):
                raise TypeScriptContractError(
                    f"Schema {name!r} must be an object."
                )

            lines.extend(
                self._render_schema(
                    name,
                    schema,
                )
            )
            lines.append("")

        return "\n".join(lines).rstrip() + "\n"

    @staticmethod
    def client_to_string() -> str:
        """Generate a typed browser client."""

        return r"""/*
 * Generated browser client for Pro Vision Engine.
 * Do not edit this file manually.
 */

import type {
  CouponListResponse,
  CouponResponse,
  HealthResponse,
} from "./api-types";

export interface ProVisionApiClientOptions {
  baseUrl: string;
  fetchImplementation?: typeof fetch;
}

export class ProVisionApiError extends Error {
  readonly status: number;
  readonly body: unknown;

  constructor(
    message: string,
    status: number,
    body: unknown,
  ) {
    super(message);
    this.name = "ProVisionApiError";
    this.status = status;
    this.body = body;
  }
}

export class ProVisionApiClient {
  private readonly baseUrl: string;
  private readonly fetchImplementation: typeof fetch;

  constructor(options: ProVisionApiClientOptions) {
    this.baseUrl = options.baseUrl.replace(/\/+$/, "");
    this.fetchImplementation =
      options.fetchImplementation ?? fetch;
  }

  getHealth(): Promise<HealthResponse> {
    return this.get<HealthResponse>("/api/v1/health");
  }

  listCoupons(): Promise<CouponListResponse> {
    return this.get<CouponListResponse>("/api/v1/coupons");
  }

  getCoupon(gameType: string): Promise<CouponResponse> {
    const encodedGameType = encodeURIComponent(gameType);

    return this.get<CouponResponse>(
      `/api/v1/coupons/${encodedGameType}`,
    );
  }

  private async get<T>(path: string): Promise<T> {
    const response = await this.fetchImplementation(
      `${this.baseUrl}${path}`,
      {
        method: "GET",
        headers: {
          Accept: "application/json",
        },
      },
    );

    const body = await this.readBody(response);

    if (!response.ok) {
      throw new ProVisionApiError(
        `Pro Vision API request failed with status ${response.status}.`,
        response.status,
        body,
      );
    }

    return body as T;
  }

  private async readBody(
    response: Response,
  ): Promise<unknown> {
    if (response.status === 204) {
      return null;
    }

    const contentType =
      response.headers.get("content-type") ?? "";

    if (contentType.includes("application/json")) {
      return response.json();
    }

    return response.text();
  }
}
"""

    @staticmethod
    def index_to_string() -> str:
        """Generate the public TypeScript export file."""

        return """/*
 * Generated public exports for the Pro Vision frontend contract.
 */

export * from "./api-client";
export * from "./api-types";
"""

    def write(
        self,
        openapi_schema: dict[str, Any],
        destination_directory: str | Path,
    ) -> tuple[Path, Path, Path]:
        """Write all frontend contract files."""

        destination = Path(
            destination_directory
        )
        destination.mkdir(
            parents=True,
            exist_ok=True,
        )

        types_path = (
            destination
            / "api-types.ts"
        )
        client_path = (
            destination
            / "api-client.ts"
        )
        index_path = (
            destination
            / "index.ts"
        )

        types_path.write_text(
            self.types_to_string(
                openapi_schema
            ),
            encoding="utf-8",
        )
        client_path.write_text(
            self.client_to_string(),
            encoding="utf-8",
        )
        index_path.write_text(
            self.index_to_string(),
            encoding="utf-8",
        )

        return (
            types_path,
            client_path,
            index_path,
        )

    @staticmethod
    def _component_schemas(
        openapi_schema: dict[str, Any],
    ) -> dict[str, Any]:
        """Read reusable schemas from an OpenAPI document."""

        if not isinstance(
            openapi_schema,
            dict,
        ):
            raise TypeError(
                "TypeScriptContractExporter requires "
                "an OpenAPI dictionary."
            )

        try:
            schemas = openapi_schema[
                "components"
            ]["schemas"]
        except (KeyError, TypeError) as error:
            raise TypeScriptContractError(
                "OpenAPI document is missing "
                "components.schemas."
            ) from error

        if not isinstance(schemas, dict):
            raise TypeScriptContractError(
                "OpenAPI components.schemas "
                "must be an object."
            )

        return schemas

    def _render_schema(
        self,
        name: str,
        schema: dict[str, Any],
    ) -> list[str]:
        """Render one named schema."""

        lines: list[str] = []
        description = schema.get(
            "description"
        )

        if (
            isinstance(description, str)
            and description.strip()
        ):
            normalized = " ".join(
                description.replace(
                    "*/",
                    "* /",
                ).split()
            )

            lines.extend(
                [
                    "/**",
                    f" * {normalized}",
                    " */",
                ]
            )

        if (
            schema.get("type") == "object"
            or "properties" in schema
        ):
            lines.extend(
                self._render_interface(
                    name,
                    schema,
                )
            )
        else:
            lines.append(
                f"export type {name} = "
                f"{self._to_type(schema)};"
            )

        return lines

    def _render_interface(
        self,
        name: str,
        schema: dict[str, Any],
    ) -> list[str]:
        """Render an object schema as an interface."""

        properties = schema.get(
            "properties",
            {},
        )
        required_values = schema.get(
            "required",
            [],
        )

        if not isinstance(
            properties,
            dict,
        ):
            raise TypeScriptContractError(
                f"Schema {name!r} "
                "has invalid properties."
            )

        if not isinstance(
            required_values,
            list,
        ):
            raise TypeScriptContractError(
                f"Schema {name!r} "
                "has an invalid required list."
            )

        required = set(
            required_values
        )
        lines = [
            f"export interface {name} {{"
        ]

        for field_name in sorted(
            properties
        ):
            field_schema = properties[
                field_name
            ]

            if not isinstance(
                field_name,
                str,
            ):
                raise TypeScriptContractError(
                    f"Schema {name!r} "
                    "has a non-string field name."
                )

            if not isinstance(
                field_schema,
                dict,
            ):
                raise TypeScriptContractError(
                    f"Property "
                    f"{name}.{field_name} "
                    "must be an object."
                )

            rendered_name = (
                self._render_field_name(
                    field_name
                )
            )
            optional = (
                ""
                if field_name in required
                else "?"
            )

            lines.append(
                f"  {rendered_name}"
                f"{optional}: "
                f"{self._to_type(field_schema)};"
            )

        lines.append("}")

        return lines

    def _to_type(
        self,
        schema: dict[str, Any],
    ) -> str:
        """Convert one OpenAPI fragment to TypeScript."""

        reference = schema.get(
            "$ref"
        )

        if isinstance(
            reference,
            str,
        ):
            return reference.rsplit(
                "/",
                1,
            )[-1]

        enum_values = schema.get(
            "enum"
        )

        if isinstance(
            enum_values,
            list,
        ):
            return self._join_types(
                [
                    json.dumps(
                        value,
                        ensure_ascii=False,
                    )
                    for value in enum_values
                ],
                fallback="never",
            )

        for keyword in (
            "anyOf",
            "oneOf",
        ):
            options = schema.get(
                keyword
            )

            if isinstance(
                options,
                list,
            ):
                return self._join_types(
                    [
                        self._to_type(
                            option
                        )
                        for option in options
                        if isinstance(
                            option,
                            dict,
                        )
                    ]
                )

        all_of = schema.get(
            "allOf"
        )

        if isinstance(
            all_of,
            list,
        ):
            return self._join_types(
                [
                    self._to_type(
                        option
                    )
                    for option in all_of
                    if isinstance(
                        option,
                        dict,
                    )
                ],
                separator=" & ",
            )

        schema_type = schema.get(
            "type"
        )

        if schema_type == "array":
            items = schema.get(
                "items",
                {},
            )

            if not isinstance(
                items,
                dict,
            ):
                return "Array<unknown>"

            return (
                "Array<"
                f"{self._to_type(items)}"
                ">"
            )

        if schema_type == "object":
            additional = schema.get(
                "additionalProperties"
            )

            if isinstance(
                additional,
                dict,
            ):
                return (
                    "Record<string, "
                    f"{self._to_type(additional)}>"
                )

            return "Record<string, unknown>"

        mapping = {
            "string": "string",
            "integer": "number",
            "number": "number",
            "boolean": "boolean",
            "null": "null",
        }

        if isinstance(
            schema_type,
            list,
        ):
            return self._join_types(
                [
                    mapping.get(
                        item,
                        "unknown",
                    )
                    for item in schema_type
                ]
            )

        return mapping.get(
            schema_type,
            "unknown",
        )

    def _render_field_name(
        self,
        field_name: str,
    ) -> str:
        """Render a valid TypeScript field name."""

        if self._identifier_pattern.fullmatch(
            field_name
        ):
            return field_name

        return json.dumps(
            field_name,
            ensure_ascii=False,
        )

    @staticmethod
    def _join_types(
        values: list[str],
        *,
        separator: str = " | ",
        fallback: str = "unknown",
    ) -> str:
        """Join unique TypeScript types."""

        unique_values = list(
            dict.fromkeys(values)
        )

        if not unique_values:
            return fallback

        return separator.join(
            unique_values
        )